# Generated by Django 4.1.4 on 2022-12-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('type', models.CharField(max_length=255, verbose_name='Артикул')),
                ('status', models.CharField(choices=[('IN_STOCK', 'В наличии'), ('ON_ORDER', 'Под заказ'), ('EXCEPTED_TO_ARRIVE', 'Ожидается поступление'), ('NOT_AVAILABLE', 'Нет в наличии'), ('NOT_PRODUCED', 'Не производится')], max_length=18, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
